#!/bin/csh -f

echo $argv
source /proj/deneb1/wa/$USER/scr/var.setup $argv

setenv runID            $TOP.$LIB.$rcCorner.$XTALK.$OCV.$Mode.$ID.$TimeStamp
setenv RptDIR		./$runID/rpt
setenv SessionDIR	./$runID/session
setenv logfile 		$runID/pt.log
setenv cmdfile		$runID/pt.cmd
if  ($SDC == 0) setenv SDC ${SdcDIR}/${TOP}/${TOP}.${Mode}.sdc

if (! -d $runID ) mkdir $runID
if (! -f .synopsys_pt.setup) ln -s $StaDIR/.synopsys_pt.setup .

pt_shell -sgq $SGQ -sgm $SGM -sgc $SGC -f $StaDIR/slave.tcl 

